
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DATATYPE EQUALS IDENTIFIER LBRACKET NEW NUMBER POINTER RBRACKET SEMICOLONstatement : DATATYPE POINTER IDENTIFIER EQUALS NEW DATATYPE LBRACKET NUMBER RBRACKET SEMICOLON'
    
_lr_action_items = {'DATATYPE':([0,6,],[2,7,]),'$end':([1,11,],[0,-1,]),'POINTER':([2,],[3,]),'IDENTIFIER':([3,],[4,]),'EQUALS':([4,],[5,]),'NEW':([5,],[6,]),'LBRACKET':([7,],[8,]),'NUMBER':([8,],[9,]),'RBRACKET':([9,],[10,]),'SEMICOLON':([10,],[11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> DATATYPE POINTER IDENTIFIER EQUALS NEW DATATYPE LBRACKET NUMBER RBRACKET SEMICOLON','statement',10,'p_statement','yacc.py',6),
]
