
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON CONDITION EXPRESSION1 EXPRESSION2 QUESTIONMARK SEMICOLON\n    statement : CONDITION QUESTIONMARK EXPRESSION1 COLON EXPRESSION2 SEMICOLON\n    '
    
_lr_action_items = {'CONDITION':([0,],[2,]),'$end':([1,7,],[0,-1,]),'QUESTIONMARK':([2,],[3,]),'EXPRESSION1':([3,],[4,]),'COLON':([4,],[5,]),'EXPRESSION2':([5,],[6,]),'SEMICOLON':([6,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> CONDITION QUESTIONMARK EXPRESSION1 COLON EXPRESSION2 SEMICOLON','statement',6,'p_statement','yacc.py',7),
]
